### ISSUE TITLE
没有支持 这个版本的吗 https://shadcn-solid.com/

### ISSUE THREAD

**Issue by bytegolang** [selemondev/vscode-shadcn-solid#16]
我一直以为是 [shadcn-solid](https://shadcn-solid.com/)  安装后却是 [solud-ui](https://solid-ui.com/)，有无计划支持 [shadcn-solid](https://shadcn-solid.com/)

**Comment by selemondev** [comment]
是的，有计划。在下一个版本中，所有组件将是 Shadcn-Solid 组件，而不是 Solid UI.

**Comment by selemondev** [comment]
嘿 @bytegolang，vscode-shadcn-solid 现在支持 shadcn-solid 和 solid-ui 啦 🥳！
